name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Copy files to server
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./docker-compose.yml ec2-user@${{ secrets.HOST }}:/home/ec2-user/app/
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./vote/ ec2-user@${{ secrets.HOST }}:/home/ec2-user/app/vote/
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./result/ ec2-user@${{ secrets.HOST }}:/home/ec2-user/app/result/

    - name: Deploy stack
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.HOST }} << 'EOF'
          cd /home/ec2-user/app/
          docker stack deploy -c docker-compose.yml myapp
        EOF
