name: Deploy to EC2 (Docker Swarm)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 3.81.142.204 >> ~/.ssh/known_hosts

      - name: Deploy to EC2 via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@3.81.142.204 << 'EOF'
            cd ~/my-voting-app
            git pull origin main
            docker stack deploy -c docker-stack.yml voting
          EOF
